### PR TITLE
please create indingo-devel branch and release them

### PR DESCRIPTION
**Pull request by k-okada**
move_base has been changed for indigo and we need to update rviz config file to support them
- fix views
- add laserscan, local and global costmap
- display footprint with blue

### CODE REVIEW

**Comment by k-okada** [comment]
screenshot from 2015-10-19 20 35 24

**Comment by DLu** [comment]
New branch created, although I'm not sure how to change the branch that the indigo debs are built from. @wjwwood ?

**Comment by tfoote** [comment]
@DLu Run bloom using the --edit-track option to get prompts to change the parameters

**Comment by mikeferguson** [comment]
I usually just edit the tracks.yaml directly -- regardless, if we get this merged in, I can take care of releasing this (that's pretty quick)

**Comment by mikeferguson** [comment]
I'm not sure we can re-target this onto indigo-devel -- you might have to recreate the PR against the new branch

**Comment by wjwwood** [comment]
Either option provided by @tfoote or @mikeferguson should work.

**Comment by k-okada** [comment]
Thanks, I re-create PR targeting to the indigo branch at #6

**Pull request closed without merging**
